### ISSUE TITLE
Slow down over TRAMP

### ISSUE THREAD

**Issue by matzebond** [akreisher/eshell-syntax-highlighting#11]
When in a remote directory eshell-syntax-highlighting slows down eshell considerably and I experience input lag.
The profile i ran suggests that file-exists-p might be responsible for this.
```
         962  55% - eshell-syntax-highlighting--enable-highlighting
         955  55%  - eshell-syntax-highlighting--parse-and-highlight
         949  54%   - eshell-syntax-highlighting--parse-command
         708  40%    - eshell-syntax-highlighting--parse-and-highlight
         521  30%     - eshell-syntax-highlighting--parse-and-highlight
         367  21%      - eshell-syntax-highlighting--parse-and-highlight
         305  17%       - eshell-syntax-highlighting--parse-and-highlight
         241  13%        - eshell-syntax-highlighting--parse-and-highlight
         226  13%         - file-exists-p
         226  13%          + tramp-file-name-handler
           5   0%           eshell-syntax-highlighting--highlight
          60   3%        + file-exists-p
          62   3%       + file-exists-p
         136   7%      + file-exists-p
         174  10%     + file-exists-p
           3   0%       eshell-syntax-highlighting--highlight
         173   9%    + file-directory-p
          62   3%    + executable-find
```

**Comment by akreisher** [comment]
Unfortunately, this is a problem with the fact that eshell/the elisp code here is running on the local session, but needs to make requests (such as file-exists-p) to the remote machine. If the connection is high-latency, this can result in the experienced slow-downs. This is different from something like syntax highlighting in ZSH, since that would run entirely in the remote machine, only passing back color codes as a result of highlighting.

This means that remote requests are made on most keystrokes as we check the prompt text. Emacs/TRAMP caches values for most things, so if you backspace and retype there should be less delay, but this won't help in general as you type new text into the prompt. A solution might involve running highlighting when idle or asynchronously after the user types, but this would take a bit more effort than I have time for now.

For now, I pushed some commits which disables syntax highlighting in remote by default. It can be re-enable with a customization variable: `eshell-syntax-highlighting-highlight-in-remote-dirs`.
