### ISSUE TITLE
Inappropriate highlighting in shells or other interactive commands

### ISSUE THREAD

**Issue by lucius-martius** [akreisher/eshell-syntax-highlighting#17]
After commit https://github.com/akreisher/eshell-syntax-highlighting/commit/a9a0ae9fab3a0bc3c0105be876b56c46d963982c this package seems to be trying to highlight the last line unconditionally.

This is an issue mostly with interactive commands like shells (for example running bash under eshell) or package managers asking for confirmation (y|n) which most often leads to the first word in the line highlighted red (unknown command). Sometimes this may happen only after switching the window and back or clicking with the mouse.

![Screenshot_20240428_004852](https://github.com/akreisher/eshell-syntax-highlighting/assets/10165955/ca415e1f-2f85-45f8-b713-3cb9dbd8ab81)

What I think is happening is that before the commit highlighting was conditional on eshell-prompt-regexp being matched at the current line, while now `(eshell-prompt-next)` will just unconditionally drop point to the last line and highlighting will occur unconditionally.

I have reverted the change locally and can verify that it fixes the issue. If indeed eshell-prompt-regexp is going to be deprecated as the commit states, I would suggest finding another way to make highlighting conditional on point being at an actual prompt.

I'm using emacs 29.3 and eat, but I can reproduce the issue with and without eat:

Steps to reproduce:
+ Start `emacs -Q`
+ M-x eshell-syntax-highlighting-global-mode
+ M-x eshell
+ ~ $ bash
+ \<backspace\>

Expected results:
No highlighting takes place until bash is left and the next eshell prompt is entered.

Observed results:
The first word of bash prompt is highlighted.

**Comment by akreisher** [comment]
Hi, thanks for reporting!

I can recreate this on emacs 29.3. I believe the issue here is that (eshell-next-prompt) finds the bash prompt because it matches `eshell-prompt-regexp`.

On the emacs `master` branch, commit https://github.com/emacs-mirror/emacs/commit/c257fd3a406d6aa83be60b96217e42b49b62cf5f (to be released with Emacs 30) fixes the false positive prompt matching in eshell output by being more explicit as to what the prompt is with dedicated text properties. This commit generally fixes the issue here, but I will  of course push an update for previous emacs versions.

I believe what I can do to fix this for now is to disable highlighting if there is a running foreground command, because highlighting only really needs to be reapplied when editing the active prompt, and there is none in this case.

**Comment by akreisher** [comment]
Hi, I pushed this commit: https://github.com/akreisher/eshell-syntax-highlighting/commit/46a7c62ae125a451ca38080eb5dcd7d147838da7, which fixes this issue for me on emacs <30.

If the problem persists after updating for whatever reason, please reopen, and again, thanks for reporting!
