### ISSUE TITLE
the highlight face doesn't show up, selection is invisible

### ISSUE THREAD

**Issue by ggegoge** [akreisher/eshell-syntax-highlighting#7]
Hi,
first of all I really appreciate this package of yours. It makes Eshell look much better especially when writing elisp inside of it.

But I've stumbled upon an issue. Apparently region selection doesn't work (it is invisible) when the `eshell-syntax-highlighting-mode` is enabled. I try to use `C-SPC` to set a mark and then I move my cursor to select a region but the selection doesn't appear. It _is selected_ though -- if I _select_ a region (without seeing it) and then try to kill it, it works and I can yank it back. The whole issue is that I don't see it highlighted, the `highlight` face doesn't seem to appear in the Eshell buffer.

On a side note -- when I enable the `prettify-symbols-mode` in the Eshell buffer it doesn't seem to work. My `lambda`s inside of lisp expressions don't change into those fancy greek lambdas. Should I file a separate issue report?

**Comment by akreisher** [comment]
For the `prettify-symbols-mode`, you need to set `prettify-symbols-alist` to the appropriate symbol mapping for the major mode. I believe the lambdas in `emacs-lisp-mode` are converted back to text when copied to the eshell buffer. I think this may do the trick:
```
(add-hook 'eshell-mode-hook
	  (lambda () (setq-local prettify-symbols-alist '(("lambda" . 955)))))
```

For the region issue, I believe this is probably due to how the `eshell-syntax-highlighting--highlight` function strips the existing face [in this line](https://github.com/akreisher/eshell-syntax-highlighting/blob/eeace52ebb2c730f3665fb235017cd57dc6050a2/eshell-syntax-highlighting.el#L118). I expect we should be able to just keep the face highlighted here if the region is active. I will look into how to do this properly when I have a bit more time.

**Comment by ggegoge** [comment]
Hi, 
thank you for the response. 

About prettification: I know that it works when copying elisp from an elisp buffer into the Eshell. When writing in the Eshell it doesn't work though. 

I have tried to use your code modifying the `prettify-symbols-list` variable but then whenever I entered the `prettify-symbols-mode` in Eshell (be it with first enabling `global-prettify-symbols-mode` and then entering Eshell or entering Eshell and only then enabling the minor mode locally) all the face colours would disappear. Even my prompt which had a colourful part has lost it's colour -- the faces defaulted to `default` same with all the highlighting from your package. Perhaps the issue has something to do with Eshell and the minor mode in question in general

**Comment by akreisher** [comment]
I've addressed this issue in https://github.com/akreisher/eshell-syntax-highlighting/commit/4416a179afff821beabf2cbd728534e4130e4eff by simply disabling highlighting when the region is active. Seems to work well enough.

For the `prettify-symbols-mode` issue, it may have to do with the fact that neither eshell or this package use `font-lock`. If `prettify-symbol- mode` messes with your prompt even without this package enabled, I expect it is `prettify-symbol-mode` calling font-lock methods, overriding prompt/syntax highlighting.

**Comment by ggegoge** [comment]
Just upgraded the package and the highlighting works. Thanks!
